[workspace]
resolver = "2"

members = [
    "tuprs",
    "tuporc",
    "tupetw",
    "tupdb",
    "tuptrace", "tuppaths", "tupcompat"]


[profile.release]
lto = true

[profile.release-with-debug]
inherits = "release"
debug = true
